//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JuntosPorUnaSonrisa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ANTECEDENTE_QUIRURGICO
    {
        public int ID_FICHA_MEDICA { get; set; }
        public string ANT_QUIREFLUJO { get; set; }
        public string ANT_QUITIROIDEAS { get; set; }
        public string ANT_QUIESTRENIMIENTO { get; set; }
        public string ANT_QUIDIARREA { get; set; }
        public string ANT_QUINEUMONIA { get; set; }
        public string ANT_QUIBRONQUIOLITIS { get; set; }
        public string ANT_QUICRUP { get; set; }
        public string ANT_QUIINFEVISURINARIAS { get; set; }
        public string ANT_QUIVARICELA { get; set; }
        public string ANT_QUIESCARLATINA { get; set; }
        public string ANT_QUIDOLORCABEZA { get; set; }
        public string ANT_QUINERVIOCISMO { get; set; }
        public string ANT_QUICONVULCIONES { get; set; }
        public string ANT_QUITRANSFUCIONES { get; set; }
        public string ANT_QUIALERGIAS { get; set; }
        public string ANT_QUIFRACTURAS { get; set; }
        public string ANT_QUIACCIDENTES { get; set; }
        public string ANT_QUICANCER { get; set; }
        public string ANT_HOSPITALIZACION { get; set; }
        public string CIRUGIAS { get; set; }
    }
}
