//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JuntosPorUnaSonrisa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ANTECEDENTE_PERINATAL
    {
        public int ID_FICHA_MEDICA { get; set; }
        public string ANT_NUMERO_EMBARAZO { get; set; }
        public string ANT_EMBARAZO_MULTIPLE { get; set; }
        public string ANT_TOMA_MEDICAMENTOS { get; set; }
        public string ANT_QUE_MEDICAMENTOS { get; set; }
        public string ANT_TOMA_VITAMINAS { get; set; }
        public string ANT_QUE_VITAMINAS { get; set; }
        public string ANT_DURACION_EMBARAZO { get; set; }
        public string ANT_FUMO_TOMO { get; set; }
        public string ANT_PARTO_NORMAL { get; set; }
        public string ANT_OBSERVACION_PARTO { get; set; }
        public string ANT_PESO { get; set; }
        public string ANT_TALLA { get; set; }
        public string ANT_PERIMETRO_CEFALICO { get; set; }
        public string ANT_TAMIZ_METABOLICO { get; set; }
        public string ANT_TAMIZ_AUDITIVO { get; set; }
        public string ANT_PARTO_COMPLICACION { get; set; }
        public string ANT_OBSERVACION_COMP_PARTO { get; set; }
        public string ANT_TOMO_SENO_MATERNO { get; set; }
        public string ANT_TIEMPO_SENO { get; set; }
        public string ANT_TOMO_FORMULA { get; set; }
        public string ANT_QUE_FORMULA { get; set; }
    }
}
