//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JuntosPorUnaSonrisa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ANTECEDENTE_NEUROPSICOLOGICO
    {
        public int ID_FICHA_MEDICA { get; set; }
        public string NEU_CONDUCTACASA { get; set; }
        public string NEU_CCASAEDAD { get; set; }
        public string NEU_CONDUCTAESCUELA { get; set; }
        public string NEU_CESCUELAEDAD { get; set; }
        public string NEU_APROVECHAMIENTO { get; set; }
        public string NEU_AEDAD { get; set; }
        public string NEU_PIERDEEQUILIBRIO { get; set; }
        public string NEU_EQUILIBRIOEDAD { get; set; }
        public string NEU_DHABLAR { get; set; }
        public string NEU_DHEDAD { get; set; }
        public string NEU_CSUENO { get; set; }
        public string NEU_CSUENOEDAD { get; set; }
        public string NEU_DNOCHE { get; set; }
        public string NEU_DNOCHEEDAD { get; set; }
        public string NEU_DESMAYO { get; set; }
        public string NEU_DESMAYOEDAD { get; set; }
        public string NEU_VE { get; set; }
        public string NEU_VEEDAD { get; set; }
        public string NEU_OYE { get; set; }
        public string NEU_OYEEDAD { get; set; }
    }
}
