//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JuntosPorUnaSonrisa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ANTECEDENTE_NUTRICIONAL
    {
        public int ID_FICHA_MEDICA { get; set; }
        public string ANT_NUT_PESO { get; set; }
        public string ANT_NUT_ESTATURA { get; set; }
        public string ANT_NUT_IMC { get; set; }
        public string ANT_NUT_COMSOLIEDAD { get; set; }
        public string ANT_NUT_TIPO_COMIDA { get; set; }
        public string ANT_NUT_DIETA_ESPECIAL { get; set; }
        public string ANT_NUT_TIPO_DIETA { get; set; }
        public string ANT_NUT_COMIDA { get; set; }
    }
}
