//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JuntosPorUnaSonrisa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ANTECEDENTE_ODONTO_FAMILIAR
    {
        public int ID_ODONTO { get; set; }
        public string ALERGIAANTIBIOTICO { get; set; }
        public string ALERGIAANESTECIA { get; set; }
        public string HEMORRAGIAS { get; set; }
        public string VIH { get; set; }
        public string TUBERCULOSIS { get; set; }
        public string ASMA { get; set; }
        public string DIABETES { get; set; }
        public string HIPERTENCION { get; set; }
        public string ENFCARDIACA { get; set; }
        public string ESPECIFIQUE { get; set; }
    }
}
