//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JuntosPorUnaSonrisa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ANTECEDENTE_FAMILIAR
    {
        public int ID_FICHA_MEDICA { get; set; }
        public string ANT_FAMILIAR { get; set; }
        public string ANT_NOMBRE { get; set; }
        public string ANT_SANO { get; set; }
        public string ANT_ENFERMEDAD { get; set; }
        public string ANT_FALLECIDO { get; set; }
        public string ANT_CAUSA { get; set; }
        public string ANT_FUMA { get; set; }
        public string ANT_TOMA { get; set; }
        public string ANT_DROGA { get; set; }
    }
}
