//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JuntosPorUnaSonrisa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONSENTIMIENTO_INFORMADO
    {
        public int ID_CONS_INFORMADO { get; set; }
        public string CONS_NOMBRE_INSTITUCION { get; set; }
        public string CONS_NOMBRE_RESPONSABLE { get; set; }
        public string CONS_TELEFONO_RESPONSABLE { get; set; }
        public string CONS_EMAIL_RESPONSABLE { get; set; }
    }
}
