//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JuntosPorUnaSonrisa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONSULTA
    {
        public int CONS_ID { get; set; }
        public Nullable<System.DateTime> CONS_FECHA { get; set; }
        public string CONS_MOTIVO { get; set; }
        public string CONS_DIAGNOSTICO { get; set; }
    }
}
