//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JuntosPorUnaSonrisa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DESARROLLO_PSICOMOTOR
    {
        public int ID_FICHA_MEDICA { get; set; }
        public string PSI_SOSTUVO_CABEZA { get; set; }
        public string PSI_SONRIO { get; set; }
        public string PSI_BALBUCEO { get; set; }
        public string PSI_SENTO { get; set; }
        public string PSI_GATEO { get; set; }
        public string PSI_CAMINO_AYUDA { get; set; }
        public string PSI_CAMINO_SOLO { get; set; }
        public string PSI_DESEMPENHO_ESCOLAR { get; set; }
    }
}
