//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JuntosPorUnaSonrisa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EXA_SYS_ESTOMATOGMATICO
    {
        public int ID_ODONTO { get; set; }
        public string LABIOS { get; set; }
        public string MEJILLAS { get; set; }
        public string MAXILAR_SUPERIOR { get; set; }
        public string MAXILAR_INFERIOR { get; set; }
        public string LENGUA { get; set; }
        public string PALADAR { get; set; }
        public string PISO { get; set; }
        public string CARRILLOS { get; set; }
        public string GLANDULAS_SALIVALES { get; set; }
        public string ORO_FARINGE { get; set; }
        public string ATM { get; set; }
        public string GANGLIOS { get; set; }
    }
}
