//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JuntosPorUnaSonrisa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EXPLORACION_FISICA
    {
        public int ID_FICHA_MEDICA { get; set; }
        public string EXPFIS_TA { get; set; }
        public string EXPFIS_TEMPERATURA { get; set; }
        public string EXPFIS_FRECUENCARD { get; set; }
        public string EXPFIS_PULSO { get; set; }
        public string EXPFIS_RESPIRATORIA { get; set; }
        public string EXPFIS_CABEZA { get; set; }
        public string EXPFIS_CUELLO { get; set; }
        public string EXPFIS_TORAX { get; set; }
        public string EXPFIS_ABDOMEN { get; set; }
        public string EXPFIS_GENITALES { get; set; }
        public string EXPFIS_NEUROLOGICO { get; set; }
        public string EXPFIS_EXAMENRECTAL { get; set; }
        public string EXPFIS_PELVICO { get; set; }
        public string EXPFIS_EXTREMIDADES { get; set; }
    }
}
