//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JuntosPorUnaSonrisa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FRECUENCIA
    {
        public int ID_FICHA_MEDICA { get; set; }
        public string FRUTAS { get; set; }
        public string VERDURAS { get; set; }
        public string LECHEENTERA { get; set; }
        public string LECHEDESLACTOSADA { get; set; }
        public string YOGURT { get; set; }
        public string YOGURTFRUTAS { get; set; }
        public string QUESO { get; set; }
        public string QUESOA { get; set; }
        public string EMBUTIDOS { get; set; }
        public string HUEVO { get; set; }
        public string POLLO { get; set; }
        public string RES { get; set; }
        public string CERDO { get; set; }
        public string MARISCOS { get; set; }
        public string VISCERAS { get; set; }
        public string LEGUMINOSAS { get; set; }
        public string AGUA { get; set; }
        public string BEBIDASA { get; set; }
        public string SNACKD { get; set; }
        public string SNACKS { get; set; }
    }
}
