//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JuntosPorUnaSonrisa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HISTORIAL_FICHA
    {
        public int ID_HISTORIAL { get; set; }
        public int ID_FICHA_MEDICA { get; set; }
        public Nullable<System.DateTime> FIC_MED_FECHA { get; set; }
        public string FICHAEXAMENLAVOR { get; set; }
        public string FICHATERAPEUTA { get; set; }
        public string FICHADIAGNOSTICO { get; set; }
        public string FICHACOMENTARIO { get; set; }
        public string FICHACOMENTMEDICO { get; set; }
        public string FICHAPADECIMIENTOACT { get; set; }
    }
}
