//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JuntosPorUnaSonrisa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HORARIO
    {
        public int HORA_ID { get; set; }
        public string HORA_DIAS { get; set; }
        public string HORA_INGRESO { get; set; }
        public string HORA_SALIDA { get; set; }
    }
}
