//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JuntosPorUnaSonrisa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class INDICADORES_SALUDB
    {
        public int ID_ODONTO { get; set; }
        public string PD_16 { get; set; }
        public string PD_17 { get; set; }
        public string PD_55 { get; set; }
        public string PD_11 { get; set; }
        public string PD_21 { get; set; }
        public string PD_51 { get; set; }
        public string PD_26 { get; set; }
        public string PD_27 { get; set; }
        public string PD_65 { get; set; }
        public string PD_36 { get; set; }
        public string PD_37 { get; set; }
        public string PD_75 { get; set; }
        public string PD_31 { get; set; }
        public string PD_41 { get; set; }
        public string PD_71 { get; set; }
        public string PD_46 { get; set; }
        public string PD_47 { get; set; }
        public string PD_85 { get; set; }
        public string PLACA16_55 { get; set; }
        public string PLACA11_51 { get; set; }
        public string PLACA26_65 { get; set; }
        public string PLACA36_75 { get; set; }
        public string PLACA31_71 { get; set; }
        public string PLACA46_85 { get; set; }
        public string CALDULO16_55 { get; set; }
        public string CALCULO11_51 { get; set; }
        public string CALCULO26_65 { get; set; }
        public string CALCULO36_75 { get; set; }
        public string CALCULO31_71 { get; set; }
        public string CALCULO46_85 { get; set; }
        public string GINGIVITIS16_55 { get; set; }
        public string GINGIVITIS11_55 { get; set; }
        public string GINGIVITIS26_65 { get; set; }
        public string GINGIVITIS36_75 { get; set; }
        public string GINGIVITIS31_71 { get; set; }
        public string GINGIVITIS46_85 { get; set; }
        public string TOTALPLACA { get; set; }
        public string TOTALCALCULO { get; set; }
        public string TOTALGINGIVITIS { get; set; }
        public string ENF_PERIDONTAL { get; set; }
        public string MAL_OCLUSION { get; set; }
        public string FLOUROSIS { get; set; }
        public Nullable<decimal> DC { get; set; }
        public Nullable<decimal> DP { get; set; }
        public Nullable<decimal> DO { get; set; }
        public Nullable<decimal> C { get; set; }
        public Nullable<decimal> E { get; set; }
        public Nullable<decimal> O { get; set; }
        public Nullable<decimal> TOTALCPO { get; set; }
        public Nullable<decimal> TOTALCEO { get; set; }
    }
}
