//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JuntosPorUnaSonrisa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class INT_APARATO_SISTEMA
    {
        public int ID_FICHA_MEDICA { get; set; }
        public string APA_DIGESTIVO { get; set; }
        public string APA_DIGESTIVOESPECF { get; set; }
        public string APA_CARDIOVASCULAR { get; set; }
        public string APA_CARDIOESPECIF { get; set; }
        public string APA_PULMONAR { get; set; }
        public string APA_PULMONARESPECIF { get; set; }
        public string APA_ENDOCRINO { get; set; }
        public string APA_ENDOCRINOESPECIF { get; set; }
        public string APA_URINARIO { get; set; }
        public string APA_URINARIOESPECIF { get; set; }
        public string APA_GENITAL { get; set; }
        public string APA_GENITALESPECIF { get; set; }
        public string APA_GINECOLOMENARCA { get; set; }
        public string APA_GINECOLOFUM { get; set; }
        public string APA_GINECOLORITMO { get; set; }
        public string APA_GINECOLOESPECIF { get; set; }
        public string APA_MUSCOESQUELATICO { get; set; }
        public string APA_MESQUELEESPECIF { get; set; }
        public string APA_NERVIOSO { get; set; }
        public string APA_NERVIOSOESPECIF { get; set; }
        public string APA_PSIQUIATRICO { get; set; }
        public string APA_PSIQUIATRICOESPECIF { get; set; }
    }
}
