//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JuntosPorUnaSonrisa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MEDICO
    {
        public int MED_ID { get; set; }
        public int HORA_ID { get; set; }
        public int TCON_ID { get; set; }
        public string MED_NOMBRE { get; set; }
        public string MED_APELLIDO { get; set; }
    }
}
