//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JuntosPorUnaSonrisa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ODONTOGRAMA
    {
        public int ID_ODONTO { get; set; }
        public string NDIENTE { get; set; }
        public string DESCRIPCION { get; set; }
        public string ENFERMEDAD { get; set; }
        public int IDDIENTE { get; set; }
    }
}
