//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JuntosPorUnaSonrisa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERSONA
    {
        public string ID_PERSONA { get; set; }
        public string PER_APELLIDO_PATERNO { get; set; }
        public string PER_APELLIDO_MATERNO { get; set; }
        public string PER_NOMBRES { get; set; }
        public string PER_EDAD { get; set; }
        public string PER_SEXO { get; set; }
        public string PER_RELIGION { get; set; }
        public string PER_MEDICO_TRATANTE { get; set; }
        public string PER_NOMBRE_MADRE { get; set; }
        public string EDAD_MADRE { get; set; }
        public string PER_NOMBRE_PADRE { get; set; }
        public string PER_EDAD_PADRE { get; set; }
        public string PER_CEDULA { get; set; }
    }
}
