//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JuntosPorUnaSonrisa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PLANES_DIAGNOSTICO
    {
        public int ID_ODONTO { get; set; }
        public string BIOMETRIA { get; set; }
        public string QUIMICA_SANGUINEA { get; set; }
        public string RAYOS_X { get; set; }
        public string ESPECIFIQUE { get; set; }
    }
}
