//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JuntosPorUnaSonrisa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SIGNOS_VITALES
    {
        public int ID_ODONTO { get; set; }
        public string PRESION_ARTERIAL { get; set; }
        public string FRECUENCIA_CARDIACA { get; set; }
        public string TEMPERATURA { get; set; }
        public string F_RESPIRATORIA { get; set; }
    }
}
