//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JuntosPorUnaSonrisa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRATAMIENTO
    {
        public int ID_ODONTO { get; set; }
        public int ID_SECION { get; set; }
        public Nullable<System.DateTime> FECHA { get; set; }
        public string DIAGNOSTICO { get; set; }
        public string PROCEDIMIENTOS { get; set; }
        public string PRESCRIPCIONESA { get; set; }
        public string CODIGO { get; set; }
        public string FIRMA { get; set; }
        public string ZONA { get; set; }
    }
}
