//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JuntosPorUnaSonrisa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIO_SIS
    {
        public string USR_ID { get; set; }
        public string USR_SECONDNAME { get; set; }
        public string USR_APELLIDOP { get; set; }
        public string USR_APELLIDOM { get; set; }
        public string USR_CEDULA { get; set; }
        public string USR_FIRSTNAME { get; set; }
        public string USR_ROLES { get; set; }
        public string USR_CONTRASENA { get; set; }
        public string USR_ESTADO { get; set; }
    }
}
