//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JuntosPorUnaSonrisa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VACUNA
    {
        public int ID_FICHA_MEDICA { get; set; }
        public string VAC_TUBERCULOSIS { get; set; }
        public string VAC_POLIO { get; set; }
        public string VAC_POLIOCUANTAS { get; set; }
        public string VAC_PENTAVALENTE { get; set; }
        public string VAC_PENTAVALENTECUANTAS { get; set; }
        public string VAC_TRIPLEVIRAL { get; set; }
        public string VAC_TRIPLEVIRALCUANTAS { get; set; }
        public string VAC_VARICELA { get; set; }
        public string VAC_NEUMOCOCOS { get; set; }
        public string VAC_HEPATITIS { get; set; }
        public string VAC_INFLUENZA { get; set; }
        public string VAC_ROTAVIRUS { get; set; }
        public string VAC_OTRAS { get; set; }
        public string VAC_OTRASESPECIFIQUE { get; set; }
    }
}
