//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JuntosPorUnaSonrisa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VALORACION_FUNCIONAL
    {
        public int ID_FICHA_MEDICA { get; set; }
        public string VAL_APOYO_ESPECIAL { get; set; }
        public string VAL_AUDITIVO { get; set; }
        public string VAL_MOTOR { get; set; }
        public string VAL_VISUAL { get; set; }
        public string VAL_IDIOMA { get; set; }
        public string VAL_OTRO { get; set; }
        public string VAL_ESPECIFICACION { get; set; }
    }
}
